//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Begin.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_BEGIN_DIALOG                102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_LOGIN                129
#define IDD_DIALOG_SELL                 130
#define IDR_MENU_MAIN                   131
#define IDD_DIALOG_WORKER               133
#define IDD_BUSSI_INFO                  134
#define IDD_STORE_INFO                  137
#define IDD_RECORD_SELL                 138
#define IDD_DIALOG_UPDATE               139
#define IDD_RECORD_UPDATE               140
#define IDD_BUSSI_ADD                   141
#define IDD_WORKER_ADD                  143
#define IDD_DIALOG_PAST                 145
#define IDD_RECORD_PAST                 146
#define IDD_DIALOG_BARE                 147
#define IDB_BITMAP1                     150
#define IDB_BMP_LOGIN                   150
#define IDI_ICON1                       154
#define IDI_ICON_BEGIN                  154
#define IDC_EDIT_ID                     1000
#define IDC_EDIT_KEY                    1001
#define IDC_BUTTON_LOGIN                1002
#define IDC_BUTTON_CANCEL               1003
#define IDC_LIST_BEGIN                  1006
#define IDR_BEGIN_CODE                  1007
#define IDR_BEGIN_NAME                  1008
#define IDR_BEGIN_EFF                   1009
#define IDE_BEGIN_SEARCH                1010
#define IDC_EDIT1                       1010
#define IDE_SELL_CODE                   1010
#define IDE_SELL_SUMMNY                 1010
#define IDE_UPDATE_SEARCH               1010
#define IDE_BUSSI_CODE                  1010
#define IDE_BACKUP                      1010
#define IDE_STORE_TNUM                  1010
#define IDC_CHECK_DIM                   1011
#define IDE_SELL_SPRICE                 1011
#define IDE_UPDATE_SUMNUM               1011
#define IDE_BUSSI_NAME                  1011
#define IDC_CHECK_INRESULT              1012
#define IDE_SELL_NAME                   1012
#define IDE_BUSSI_PHONE                 1012
#define IDB_BEGIN_SEARCH                1013
#define IDE_SELL_SPEC                   1013
#define IDE_SELL_EFF                    1014
#define IDE_BUSSI_ADDRESS               1014
#define IDE_SELL_INGDNT                 1015
#define IDL_WORKER_INFO                 1015
#define IDE_SELL_DOSAGE                 1016
#define IDC_LIST1                       1016
#define IDL_BUSSI_INFO                  1016
#define IDE_SELL_COUNTS                 1017
#define IDL_STORE_INFO                  1017
#define IDE_BUSSI_REMARK                1017
#define IDR_STORE_ALL                   1018
#define IDR_STORE_LACK                  1019
#define IDE_SELL_NUM                    1020
#define IDR_STORE_NORMAL                1020
#define IDE_SELL_TOTALP                 1021
#define IDR_STORE_EX                    1021
#define IDE_STORE_SEARCH                1022
#define IDB_STORE_SEARCH                1023
#define IDL_RECORD_SELL                 1024
#define IDT_TIME_FROM                   1025
#define IDT_TIME_TO                     1026
#define IDB_SELL_SEARCH                 1027
#define IDR_SELL_ALL                    1030
#define IDR_SELL_LMON                   1031
#define IDR_SELL_LWEEK                  1032
#define IDR_SELL_LYEST                  1033
#define IDE_SELL                        1035
#define IDE_UPDATE_CODE                 1037
#define IDE_UPDATE_NAME                 1038
#define IDE_UPDATE_SPEC                 1039
#define IDE_UPDATE_EFF                  1040
#define IDE_UPDATE_INGDNT               1041
#define IDE_UPDATE_DOSAGE               1042
#define IDE_UPDATE_NUM                  1043
#define IDE_UPDATE_SPRICE               1045
#define IDE_UPDATE_COUNTS               1046
#define IDT_UPDATE_FROM                 1048
#define IDT_UPDATE_TO                   1049
#define IDB_UPDATE_SEARCH               1051
#define IDR_UPDATE_ALL                  1052
#define IDR_UPDATE_LMON                 1053
#define IDR_UPDATE_LWEEK                1054
#define IDR_UPDATE_LYEST                1055
#define IDL_RECODE_UPDATE               1056
#define IDE_SELL_SUMNUM                 1057
#define IDB_BUSSI_DELETE                1058
#define IDB_BUSSI_ADD                   1059
#define IDB_BUSSI_MODIFY                1061
#define IDE_WORKER_ID                   1062
#define IDE_WORKER_NAME                 1063
#define IDE_WORKER_POS                  1064
#define IDE_WORKER_PHONE                1065
#define IDB_WORKER_ADD                  1066
#define IDB_WORKER_MODIFY               1067
#define IDE_UPDATE_NEWCODE              1067
#define IDC_BUTTON3                     1068
#define IDB_WORKER_DELETE               1068
#define IDE_PAST_SEARCH                 1068
#define IDE_PAST_NAME                   1069
#define IDE_PAST_SPEC                   1070
#define IDE_PAST_INGDNT                 1071
#define IDE_PAST_EFF                    1072
#define IDE_PAST_DOSAGE                 1073
#define IDE_PAST_TOTALV                 1074
#define IDE_PAST_NUM                    1075
#define IDE_PAST_COUNTS                 1076
#define IDE_PAST_SPRICE                 1077
#define IDE_PAST_CODE                   1078
#define IDE_PAST_MARK                   1079
#define IDC_DATETIMEPICKER3             1080
#define IDT_PAST_FROM                   1081
#define IDT_PAST_TO                     1082
#define IDE_PAST                        1083
#define IDB_PAST_SEARCH                 1084
#define IDE_PAST_SUMNUM                 1085
#define IDE_PAST_SUMMNY                 1086
#define IDR_PAST_ALL                    1087
#define IDR_PAST_LMON                   1088
#define IDR_PAST_LWEEK                  1089
#define IDR_PAST_LYEST                  1090
#define IDL_RECORD_PAST                 1091
#define IDB_BACKUP                      1092
#define IDP_LONGIN                      1095
#define IDC_RADIO1                      1096
#define ID_32771                        32771
#define ID_32772                        32772
#define IDM_RECORD_SELL                 32773
#define IDM_                            32774
#define IDM_RECORD_STOCK                32775
#define ID_32776                        32776
#define ID_32777                        32777
#define ID_32778                        32778
#define ID_32779                        32779
#define ID_32780                        32780
#define ID_32781                        32781
#define IDM_ADD_DRUG                    32782
#define IDM_OD_RECORD                   32783
#define IDM_OUTD_RECORD                 32784
#define ID                              32785
#define IDM_BACKUP_REC                  32786
#define IDM_OUTD_DW                     32787
#define ID_32788                        32788
#define ID_32789                        32789
#define ID_32790                        32790
#define IDM_SELL_SELECT                 32791
#define IDM_ADD_NEWD                    32792
#define IDM_QUIT                        32793
#define IDM_STORE_INFO                  32794
#define IDM_BUSSI_INFO                  32795
#define ID_32796                        32796
#define ID_32797                        32797
#define ID_32798                        32798
#define IDM_MANAGE                      32799
#define IDM_MANAGER                     32800
#define IDM_BUYER_INFO                  32801
#define IDM_MANAGER_INFO                32802
#define IDM_SELLER_INFO                 32803
#define IDM_WORKER_INFO                 32804
#define ID_32805                        32805
#define IDM_RECORD_UPDATA               32806
#define IDM_RECORD_UPDATE               32807
#define IDM_UPDATE_DRUG                 32808
#define IDM_PAST_RECORD                 32812
#define IDM_RECORD_PAST                 32813
#define IDM_PAST_REGISTER               32814

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        155
#define _APS_NEXT_COMMAND_VALUE         32815
#define _APS_NEXT_CONTROL_VALUE         1097
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
